/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function main(): void;
export function new_sim_menu(): number;
export function join_sim_menu(): number;
export function reset_camera_menu(): number;
export function robots_in_room(): number;
export function room_id(): number;
export function show_3d_view(): void;
export function __wbg_sphereoptions_free(a: number): void;
export function __wbg_get_sphereoptions_slice(a: number, b: number): void;
export function __wbg_set_sphereoptions_slice(a: number, b: number, c: number): void;
export function __wbg_get_sphereoptions_updatable(a: number): number;
export function __wbg_set_sphereoptions_updatable(a: number, b: number): void;
export function __wbg_boxoptions_free(a: number): void;
export function __wbg_get_boxoptions_bottomBaseAt(a: number, b: number): void;
export function __wbg_set_boxoptions_bottomBaseAt(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_depth(a: number, b: number): void;
export function __wbg_set_boxoptions_depth(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_height(a: number, b: number): void;
export function __wbg_set_boxoptions_height(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_sideOrientation(a: number, b: number): void;
export function __wbg_set_boxoptions_sideOrientation(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_size(a: number, b: number): void;
export function __wbg_set_boxoptions_size(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_topBaseAt(a: number, b: number): void;
export function __wbg_set_boxoptions_topBaseAt(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_updatable(a: number): number;
export function __wbg_set_boxoptions_updatable(a: number, b: number): void;
export function __wbg_get_boxoptions_width(a: number, b: number): void;
export function __wbg_set_boxoptions_width(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_wrap(a: number): number;
export function __wbg_set_boxoptions_wrap(a: number, b: number): void;
export function __wbg_get_sphereoptions_arc(a: number, b: number): void;
export function __wbg_get_sphereoptions_diameter(a: number, b: number): void;
export function __wbg_get_sphereoptions_diameterX(a: number, b: number): void;
export function __wbg_get_sphereoptions_diameterY(a: number, b: number): void;
export function __wbg_get_sphereoptions_diameterZ(a: number, b: number): void;
export function __wbg_get_sphereoptions_segments(a: number, b: number): void;
export function __wbg_get_sphereoptions_sideOrientation(a: number, b: number): void;
export function __wbg_set_sphereoptions_arc(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_diameter(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_diameterX(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_diameterY(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_diameterZ(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_segments(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_sideOrientation(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__Fn_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hbd50058e8e3ed8a0(a: number, b: number): void;
export function _dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h5c441f227d63452f(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hea569866aad972c7(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__ha204ea0aa77d1d1c(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h2f48bc7cb1c39ec5(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h4dc266bd3929c8bd(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function wasm_bindgen__convert__closures__invoke2_mut__h18f41ff999320e94(a: number, b: number, c: number, d: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_start(): void;
