/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function main(): void;
export function step1(): number;
export function step2(): number;
export function step3(): number;
export function step4(): number;
export function __wbg_sphereoptions_free(a: number): void;
export function __wbg_get_sphereoptions_slice(a: number, b: number): void;
export function __wbg_set_sphereoptions_slice(a: number, b: number, c: number): void;
export function __wbg_get_sphereoptions_updatable(a: number): number;
export function __wbg_set_sphereoptions_updatable(a: number, b: number): void;
export function __wbg_boxoptions_free(a: number): void;
export function __wbg_get_boxoptions_bottomBaseAt(a: number, b: number): void;
export function __wbg_set_boxoptions_bottomBaseAt(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_depth(a: number, b: number): void;
export function __wbg_set_boxoptions_depth(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_height(a: number, b: number): void;
export function __wbg_set_boxoptions_height(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_sideOrientation(a: number, b: number): void;
export function __wbg_set_boxoptions_sideOrientation(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_size(a: number, b: number): void;
export function __wbg_set_boxoptions_size(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_topBaseAt(a: number, b: number): void;
export function __wbg_set_boxoptions_topBaseAt(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_updatable(a: number): number;
export function __wbg_set_boxoptions_updatable(a: number, b: number): void;
export function __wbg_get_boxoptions_width(a: number, b: number): void;
export function __wbg_set_boxoptions_width(a: number, b: number, c: number): void;
export function __wbg_get_boxoptions_wrap(a: number): number;
export function __wbg_set_boxoptions_wrap(a: number, b: number): void;
export function __wbg_set_sphereoptions_arc(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_diameter(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_diameterX(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_diameterY(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_diameterZ(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_segments(a: number, b: number, c: number): void;
export function __wbg_set_sphereoptions_sideOrientation(a: number, b: number, c: number): void;
export function __wbg_get_sphereoptions_arc(a: number, b: number): void;
export function __wbg_get_sphereoptions_diameter(a: number, b: number): void;
export function __wbg_get_sphereoptions_diameterX(a: number, b: number): void;
export function __wbg_get_sphereoptions_diameterY(a: number, b: number): void;
export function __wbg_get_sphereoptions_diameterZ(a: number, b: number): void;
export function __wbg_get_sphereoptions_segments(a: number, b: number): void;
export function __wbg_get_sphereoptions_sideOrientation(a: number, b: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__Fn_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf772fa2c72e60289(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke1__h7d4c8198b79a9d52(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf4eb020b7f4e07c1(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__h7f57539d6be0ff98(a: number, b: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h4ad26f65f79df243(a: number, b: number, c: number, d: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_start(): void;
