name: Publish

on:
  push:
    branches: ["master"]
  pull_request:

permissions:
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i && node build.js
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "."
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      - uses: actions/deploy-pages@v2
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
